name: school_see_app
description: A Flutter application for school parent registration and management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  latlong2: ^0.9.1
  flutter_map: ^8.2.2
  qr_flutter: ^4.1.0
  camera: ^0.11.2+1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  percent_indicator: ^4.2.5
  animated_text_kit: ^4.3.0
  lottie: ^3.3.2
  image_picker: ^1.2.0
  chewie: ^1.13.0
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.3
  flutter_svg: ^2.2.1
  flutter_local_notifications: ^19.5.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/